import { Platform, StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#070A11",
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "transparent",
    zIndex: 1,
  },
  loaderWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "transparent",
    zIndex: 1,
  },
  loaderText: {
    color: "#D1D5DB",
    fontSize: 14,
  },
  card: {
    borderWidth: 1,
    borderColor: "#ffffff24",
    backgroundColor: "#00000077",
    borderRadius: 26,
    padding: 22,
    gap: 12,
    zIndex: 1,
  },
  brandHeader: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  brandLogoLarge: {
    width: 72,
    height: 72,
    borderRadius: 14,
    marginBottom: 8,
  },
  brandTextLarge: {
    color: "#FFFFFFE0",
    fontSize: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.8,
  },
  title: {
    color: "#F8FAFC",
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
  subtitle: {
    color: "#FFFFFFA3",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 6,
  },
  codeLine: {
    color: "#A7F3D0",
    fontSize: 13,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ffffff22",
    borderRadius: 13,
    backgroundColor: "#0000004f",
    color: "#F8FAFC",
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
  },
  fieldLabel: {
    color: "#FFFFFF80",
    fontSize: 12,
    marginBottom: -4,
  },
  readOnlyField: {
    borderWidth: 1,
    borderColor: "#ffffff22",
    borderRadius: 13,
    backgroundColor: "#00000033",
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  readOnlyFieldText: {
    color: "#F8FAFC",
    fontSize: 16,
  },
  usernameWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffffff22",
    borderRadius: 13,
    backgroundColor: "#0000004f",
    paddingHorizontal: 14,
  },
  usernamePrefix: {
    color: "#FFFFFF80",
    fontSize: 16,
    marginRight: 2,
  },
  usernameInput: {
    flex: 1,
    color: "#F8FAFC",
    paddingVertical: 13,
    fontSize: 16,
  },
  usernameHelp: {
    color: "#FFFFFF90",
    fontSize: 12,
    marginTop: -4,
  },
  primaryButton: {
    marginTop: 8,
    borderRadius: 13,
    backgroundColor: "#FFFFFF",
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  disabledButton: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: "#0B0F18",
    fontSize: 15,
    fontWeight: "700",
  },
  errorText: {
    color: "#FCA5A5",
    fontSize: 13,
    marginTop: 2,
  },
  infoText: {
    color: "#A7F3D0",
    fontSize: 13,
    marginTop: 2,
  },
  footerText: {
    marginTop: 4,
    color: "#FFFFFFA3",
    fontSize: 13,
    textAlign: "center",
  },
  footerLink: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
});
